# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HyApp

pod 'IQKeyboardManagerSwift', '~> 6.0.4', :inhibit_warnings => true
pod 'Alamofire', '~> 4.5', :inhibit_warnings => true
pod 'SwiftyJSON', '~> 4.0', :inhibit_warnings => true
pod 'SQLite.swift', '0.11.4', :inhibit_warnings => true

end

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(FRAMEWORK_SEARCH_PATHS)']
end
end

